/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CancellationsRouteImport } from './routes/cancellations'
import { Route as CardRouteImport } from './routes/card'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkLeadGenerationAutomationRouteImport } from './routes/work.lead-generation-automation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationsRoute = CancellationsRouteImport.update({
  id: '/cancellations',
  path: '/cancellations',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLeadGenerationAutomationRoute =
  WorkLeadGenerationAutomationRouteImport.update({
    id: '/work/lead-generation-automation',
    path: '/work/lead-generation-automation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancellations': typeof CancellationsRoute
  '/card': typeof CardRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/work/lead-generation-automation': typeof WorkLeadGenerationAutomationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancellations': typeof CancellationsRoute
  '/card': typeof CardRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/work/lead-generation-automation': typeof WorkLeadGenerationAutomationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancellations': typeof CancellationsRoute
  '/card': typeof CardRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/work/lead-generation-automation': typeof WorkLeadGenerationAutomationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cancellations'
    | '/card'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/work/lead-generation-automation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancellations'
    | '/card'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/work/lead-generation-automation'
  id:
    | '__root__'
    | '/'
    | '/cancellations'
    | '/card'
    | '/cookies'
    | '/privacy'
    | '/terms'
    | '/work/lead-generation-automation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancellationsRoute: typeof CancellationsRoute
  CardRoute: typeof CardRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WorkLeadGenerationAutomationRoute: typeof WorkLeadGenerationAutomationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellations': {
      id: '/cancellations'
      path: '/cancellations'
      fullPath: '/cancellations'
      preLoaderRoute: typeof CancellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/lead-generation-automation': {
      id: '/work/lead-generation-automation'
      path: '/work/lead-generation-automation'
      fullPath: '/work/lead-generation-automation'
      preLoaderRoute: typeof WorkLeadGenerationAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancellationsRoute: CancellationsRoute,
  CardRoute: CardRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WorkLeadGenerationAutomationRoute: WorkLeadGenerationAutomationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
